# Generated by Django 3.1.4 on 2020-12-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Q_A', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='QA',
            name='context',
        ),
    ]
