# Generated by Django 3.1.4 on 2021-01-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Q_A', '0002_remove_qa_context'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qa',
            table='web_QA',
        ),
    ]
