# Generated by Django 3.1.5 on 2021-01-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Q_A', '0003_auto_20210101_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='qa',
            name='question',
            field=models.CharField(max_length=1000),
        ),
    ]
